#!/bin/bash
# Knit & Craft - Quick Commands Reference
# Fichier de référence pour les commandes essentielles

echo "════════════════════════════════════════════════════════"
echo "  🧶 Knit & Craft - Quick Commands Reference"
echo "════════════════════════════════════════════════════════"
echo ""

# 🚀 DÉMARRAGE RAPIDE
echo "🚀 DÉMARRAGE RAPIDE (5 min)"
echo "────────────────────────────"
echo ""
echo "1. Installation:"
echo "   npm install"
echo ""
echo "2. Configuration:"
echo "   # Créer .env.local avec DATABASE_URL"
echo "   # voir .env.example"
echo ""
echo "3. Initialiser BD:"
echo "   npx prisma db push"
echo ""
echo "4. Démarrer:"
echo "   npm run dev"
echo ""
echo "5. Accéder:"
echo "   http://localhost:3000"
echo ""

# 📚 DÉVELOPPEMENT
echo "📚 DÉVELOPPEMENT"
echo "────────────────"
echo ""
echo "# Démarrer serveur"
echo "npm run dev"
echo ""
echo "# Build production"
echo "npm run build"
echo ""
echo "# Start production"
echo "npm run start"
echo ""
echo "# Linter"
echo "npm run lint"
echo ""

# 🗄️ BASE DE DONNÉES
echo "🗄️ BASE DE DONNÉES"
echo "──────────────────"
echo ""
echo "# Synchroniser le schéma"
echo "npx prisma db push"
echo ""
echo "# Générer Prisma Client"
echo "npx prisma generate"
echo ""
echo "# Accéder à l'interface Prisma"
echo "npx prisma studio"
echo ""
echo "# Créer une migration"
echo "npx prisma migrate dev --name ma_migration"
echo ""
echo "# Lancer le seed (données test)"
echo "npx prisma db seed"
echo ""

# 🔧 CONFIGURATION
echo "🔧 CONFIGURATION"
echo "────────────────"
echo ""
echo "# Générer NEXTAUTH_SECRET"
echo "openssl rand -base64 32"
echo ""
echo "# Vérifier les variables d'env"
echo "cat .env.local"
echo ""

# 🧪 TESTING
echo "🧪 TESTING & DEBUG"
echo "──────────────────"
echo ""
echo "# Logs en temps réel"
echo "npm run dev  # voir console"
echo ""
echo "# Logs Vercel (production)"
echo "vercel logs [project-name] --tail"
echo ""
echo "# Tester API localement"
echo "curl http://localhost:3000/api/products"
echo ""

# 📊 MONITORING
echo "📊 MONITORING & STATS"
echo "─────────────────────"
echo ""
echo "# Voir les tables Prisma"
echo "npx prisma studio"
echo ""
echo "# Exporter données (PostgreSQL)"
echo "pg_dump \$DATABASE_URL > backup.sql"
echo ""
echo "# Restaurer données"
echo "psql \$DATABASE_URL < backup.sql"
echo ""

# 🚀 DÉPLOIEMENT
echo "🚀 DÉPLOIEMENT"
echo "──────────────"
echo ""
echo "# 1. Git push (Vercel déploie auto)"
echo "git add ."
echo "git commit -m 'Feature description'"
echo "git push origin main"
echo ""
echo "# 2. Vercel logs (watch)"
echo "vercel logs [project-name] --tail"
echo ""
echo "# 3. Pull env (local)"
echo "vercel env pull .env.local"
echo ""

# 📱 ADMIN
echo "📱 ADMIN"
echo "────────"
echo ""
echo "# Créer user admin (Prisma Studio)"
echo "npx prisma studio"
echo "# Table User > Create > role: ADMIN"
echo ""
echo "# Accéder dashboard"
echo "http://localhost:3000/admin"
echo ""

# 🛠️ UTILITAIRES
echo "🛠️ UTILITAIRES"
echo "───────────────"
echo ""
echo "# Nettoyer node_modules"
echo "rm -rf node_modules && npm install"
echo ""
echo "# Nettoyer cache Next.js"
echo "rm -rf .next"
echo ""
echo "# Format code"
echo "npm run lint --fix"
echo ""

# 📞 AIDE
echo "📞 AIDE & RESSOURCES"
echo "────────────────────"
echo ""
echo "Documentation:"
echo "  • README.md         - Vue d'ensemble"
echo "  • INSTALLATION.md   - Installation détaillée"
echo "  • DEPLOYMENT.md     - Déploiement Vercel"
echo "  • ADMIN_GUIDE.md    - Guide administrateur"
echo "  • API_DOCS.md       - Référence API"
echo ""
echo "Resources:"
echo "  • Docs NextAuth:    https://next-auth.js.org"
echo "  • Docs Prisma:      https://www.prisma.io/docs"
echo "  • Docs Next.js:     https://nextjs.org/docs"
echo "  • Docs Tailwind:    https://tailwindcss.com/docs"
echo ""

echo "════════════════════════════════════════════════════════"
echo "Pour plus d'aide, consultez la documentation en Markdown"
echo "════════════════════════════════════════════════════════"
